[book]
title = "Modular and Open-Source Science Station (MOSSS)"
authors = ["Brandon J. Winters, Ph.D., Murphy O'Malley, and Evan Streeter"]
description = "MOSSS Edge Gateway & WOILD Field Node Documentation"
language = "en"
src = "docs"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/bjw58994/Science-Station"
default-theme = "light"
preferred-dark-theme = "light"
mathjax-support = true
no-section-label = true